#
# Config.yml - Domain Referrals
# Made with love by Theo.
#
# MIT License - https://github.com/TheoBong/DomainReferrals/blob/main/LICENSE
#

DATABASE:
  # You can use either "sqlite", or "mysql" (Must use 1 of them) - SQLite works without setup.
  USE: "sqlite"

  # MySQL/MariaDB Fields - only applied if 'USE' option is set to "mysql"
  MYSQL:
    HOST: "127.0.0.1"
    PORT: 3306
    USER: "user"
    PASSWORD: "password"
    DATABASE: "referrals"

GENERAL:
  DEFAULT_REWARD_GROUP: "NORMAL"
  ORIGIN_SUBDOMAIN: "origin"

JOIN_REWARDS_GROUPS:
  NORMAL:
    MESSAGE: "You joined using a player domain. You get $500 and a commmon key!"
    COMMANDS:
      - "givekey {player} common-key"
      - "addmoney {player} 500"
  PARTNER:
    MESSAGE: "You joined using a partner domain. You get $1000 and a partner key!"
    COMMANDS:
      - "givekey {player} partner-key"
      - "addmoney {player} 1000"


#This is work in progress - does not actually work right now
INVITE_REWARDS:
  10:
    MESSAGE: "You claimed your 10 invite reward, you get $1000."
    COMMANDS:
      - "addmoney {player} 1000"
  20:
    MESSAGE: "You claimed your 20 invite reward, you get $2000."
    COMMANDS:
      - "addmoney {player} 2000"
  50:
    MESSAGE: "You claimed your 50 invite reward, you get $5000."
    COMMANDS:
      - "addmoney {player} 5000"
  100:
    MESSAGE: "You claimed your 100 invite reward, you get $10000."
    COMMANDS:
      - "addmoney {player} 10000"

#
# The End!
#

