#
# Config.yml - Domain Referrals
# Made with love by Theo.
#
# MIT License - https://github.com/TheoBong/DomainReferrals/blob/main/LICENSE
#

DATABASE:
  #Recommend using MongoDB rather than MySQL/SQLite (Required for storing data).

  # You can use either "mongo", "sqlite", or "mysql" (Must use 1 of them) - SQLite works without setup.
  USE: "sqlite"

  # MongoDB Fields - only applied if 'USE' option is set to "mongo"
  MONGO:
    LOCALHOST_NO_AUTH: false # Only use this if you know what it is, this will replace URI if enabled.
    URI: "mongodb://user:pass@127.0.0.1/punishments"
    DB: "referrals"

  # MySQL/MariaDB Fields - only applied if 'USE' option is set to "mysql"
  MYSQL:
    HOST: "127.0.0.1"
    PORT: 3306
    USER: "user"
    PASSWORD: "password"
    DATABASE: "referrals"

#
# The End!
#

