name: DomainReferrals
description: An domain referral plugin (https://github.com/TheoBong/DomainReferrals/).
version: git-DomainReferrals-49bf276
author: Theo
main: com.bongbong.referrals.ReferralsPlugin