name: DomainReferrals
description: An domain referral plugin (https://github.com/TheoBong/DomainReferrals/).
version: git-DomainReferrals-da2e31c
author: Theo
main: com.bongbong.referrals.ReferralsPlugin