name: DomainReferrals
description: An domain referral plugin (https://github.com/TheoBong/DomainReferrals/).
version: git-DomainReferrals-b2967f8
author: Theo
main: com.bongbong.referrals.ReferralsPlugin